- name: nginx install and run
  hosts: web
  become: yes  #take sudo access
  tasks: 
  - name: install nginx
    ansible.builtin.package:  #heterongenous module that can work for all distributors , here all distributors means redhat.obuntu etc, if we know its redhat can use dnf also
     name: nginx
     state: present

  - name: run nginx
    ansible.builtin.service:
     name: nginx
     state: started
     enabled: yes


